### ISSUE TITLE
Upgrade Bumps etc

### ISSUE THREAD

**Issue by 5xPa** [garethflowers/homebridge-texecom-connect#267]
HI I hope I am posting this in the correct place. I have been using Texecom-Connect for more than year, it's great. When I downloaded I select to be notified of any updates. I receive email such as 
chore(deps-dev): bump @types/node from 17.0.5 to 17.0.7 (PR #266)

How do I upgrade Texecom-connect with these updates?

Thank you for the app

**Comment by garethflowers** [comment]
A lot of those updates are just changes to the code base and so aren't released as a full upgrade.

You might be better off customising your notifications to only notify on "Releases".
