### ISSUE TITLE
Is it possible to use this with just the SmartCom and keep the app working?

### ISSUE THREAD

**Issue by booshtukka** [garethflowers/homebridge-texecom-connect#424]
Or is it necessary to get a ComIP too? I'm not having any success so far, and don't want to lose the app functionality since I don't think HomeKit can trigger a critical alarm notification.

**Comment by garethflowers** [comment]
No it's not possible to use this app and have the Texecom mobile app fully functional as well. SmartCom only provides a single connection - so it's either one or the other.

If you get another ComIP you would be able to have both.
