### ISSUE TITLE
Version 0.0.9

### ISSUE THREAD

**Issue by 5xPa** [garethflowers/homebridge-texecom-connect#525]
Good morning I have v0.0.8 installed. When login to Homebridge >> Plugins there is no option to upgrade too v0.0.9. 
Is there a commandline option to upgrade?

**Comment by garethflowers** [comment]
Looks like v0.0.9 didn't get published correctly due to some token issues. I'll look into it.

**Comment by garethflowers** [comment]
Resolved by 75198d16861163e0383439bc93551427e8ed8ad3
