### ISSUE TITLE
Ready for HomeBridge 2?

### ISSUE THREAD

**Issue by booshtukka** [garethflowers/homebridge-texecom-connect#609]
Request for developer to mark this plugin as ready for HB2, or to do whatever needs to be done to be ready. :)

**Comment by metaljay** [comment]
I am not entirely sure this is still actively maintained as the previous releases could be bot generated based on the dependancies.

I have tried another plugin here which works well to if you want to try both?
https://github.com/K1LL3R234/homebridge-texecom

**Comment by booshtukka** [comment]
Thank you!

Is it correct that you still can’t arm/disarm the alarm with the other plugin?

**Comment by metaljay** [comment]
no no, im able to arm/disarm with the other plugin.
Everything works fine :)

**Comment by booshtukka** [comment]
Amazing! Installation failed for me so I’ve filed an issue :)Sent from my iPhoneOn 8 Oct 2024, at 19:45, metaljay ***@***.***> wrote:﻿
no no, im able to arm/disarm with the other plugin.
Everything works fine :)

**Comment by garethflowers** [comment]
Resolved by 76f04e126325f8b9dfeb2bbf851d45deb2717132.

**Comment by garethflowers** [comment]
Published v0.0.11.

**Comment by metaljay** [comment]
Hi @garethflowers , are you still looking at bug fixes etc? I’m asking as there are issues raised any no responses from you but you keep posting various releases but they just appear to be dependency updates
